### ISSUE TITLE
Overview Page: Internal Server Error

### ISSUE THREAD

**Issue by JuniperSpring** [puppet-community/puppetboard#180]
Most of the tabs display content but the Overview tab has an Internal Server Error:

    Internal Server Error
    This error usually occurs because:
    We were unable to reach PuppetDB;
    The query to be executed was malformed resulting in an incorrectly encoded request.
    Please have a look at the log output for further information.

I have:
Puppetdb 3.2.0
Puppetboard v0.1.0

Here is the error I'm getting in the logs when I try to access the Overview tab:
```
DEBUG:pypuppetdb.api:_query called with endpoint: mbean, path: puppetlabs.puppetdb.query.population:type=default,name=num-nodes, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
DEBUG:pypuppetdb.api:_url called with endpoint: mbean and path: puppetlabs.puppetdb.query.population:type=default,name=num-nodes
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: localhost
DEBUG:requests.packages.urllib3.connectionpool:"GET /metrics/v1/mbeans HTTP/1.1" 200 25282
DEBUG:pypuppetdb.api:_query called with endpoint: mbean, path: puppetlabs.puppetdb.query.population:type=default,name=num-resources, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
DEBUG:pypuppetdb.api:_url called with endpoint: mbean and path: puppetlabs.puppetdb.query.population:type=default,name=num-resources
DEBUG:requests.packages.urllib3.connectionpool:"GET /metrics/v1/mbeans HTTP/1.1" 200 25282
DEBUG:pypuppetdb.api:_query called with endpoint: mbean, path: puppetlabs.puppetdb.query.population:type=default,name=avg-resources-per-node, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None
DEBUG:pypuppetdb.api:_url called with endpoint: mbean and path: puppetlabs.puppetdb.query.population:type=default,name=avg-resources-per-node
DEBUG:requests.packages.urllib3.connectionpool:"GET /metrics/v1/mbeans HTTP/1.1" 200 25282
ERROR:puppetboard.app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 155, in index
    'num_nodes': num_nodes['Value'],
KeyError: u'Value'
```

**Comment by corey-hammerton** [comment]
Can you try manually CURLing the metrics individually from your PuppetDB?

/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-nodes
/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-resources
/metrcis/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=avg-resources-per-node

**Comment by JuniperSpring** [comment]
Here is what I ran:
```
# curl -X GET -H 'Accept: application/json' http://puppetdb.com:8080/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-nodes
{
  "Value" : 1
}
```

**Comment by corey-hammerton** [comment]
I noticed this in your stack trace that you have an odd directory path to your puppetboard root. 

I'm not sure this is a cause but how did you install/update your puppetboard install? Through PIP?

**Comment by JuniperSpring** [comment]
Oops, sorry. Here are the other two:
```
# curl -X GET -H 'Accept: application/json' http://puppetdb.com:8080/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=num-resources
{
  "Value" : 293
}
# curl -X GET -H 'Accept: application/json' http://puppetdb.com:8080/metrics/v1/mbeans/puppetlabs.puppetdb.query.population:type=default,name=avg-resources-per-node
{
  "Value" : 293
}
```
I installed it using the puppet puppetboard module.

**Comment by corey-hammerton** [comment]
What version of pypuppetdb is installed?

**Comment by JuniperSpring** [comment]
I have pypuppetdb 0.2.0.
```
# pip list
distribute (0.6.10)
Flask (0.10.1)
Flask-WTF (0.12)
iniparse (0.3.1)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
ordereddict (1.2)
pip (7.1.2)
pycurl (7.19.0)
pygpgme (0.1)
pypuppetdb (0.2.0)
requests (2.8.1)
setuptools (0.6rc11)
urlgrabber (3.9.1)
virtualenv (13.1.2)
Werkzeug (0.10.4)
WTForms (2.0.2)
yum-metadata-parser (1.1.2)
```

**Comment by corey-hammerton** [comment]
You're problem is that your install is requesting specific mbeans but is NOT appending the specific mbean to the request path. 

This may seem odd but can you supply the content of the index() function in your app.py including line numbers? There is a discrepancy between the line-numbers in our source code and the line number provided in your first stack trace.

**Comment by JuniperSpring** [comment]
I apologize, the discrepancy was my fault. I added extra debugging lines before to see if I could pin down what the issue was. I had extra log.warn()s that were commented out so I had forgotten about them. They have now been removed.

The error log now says:
```
File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 149, in index
    'num_nodes': num_nodes['Value'],
KeyError: u'Value'
```

Here is the index function:
```
125 @app.route('/', defaults={'env': 'production'})
126 @app.route('/<env>/')
127 def index(env):
128     """This view generates the index page and displays a set of metrics and
129     latest reports on nodes fetched from PuppetDB.
130
131     :param env: Search for nodes in this (Catalog and Fact) environment
132     :type env: :obj:`string`
133     """
134     check_env(env)
135
136     # TODO: Would be great if we could parallelize this somehow, doing these
137     # requests in sequence is rather pointless.
138     prefix = 'puppetlabs.puppetdb.query.population'
139     num_nodes = get_or_abort(
140         puppetdb.metric,
141         "{0}{1}".format(prefix, ':type=default,name=num-nodes'))
142     num_resources = get_or_abort(
143         puppetdb.metric,
144         "{0}{1}".format(prefix, ':type=default,name=num-resources'))
145     avg_resources_node = get_or_abort(
146         puppetdb.metric,
147         "{0}{1}".format(prefix, ':type=default,name=avg-resources-per-node'))
148     metrics = {
149         'num_nodes': num_nodes['Value'],
150         'num_resources': num_resources['Value'],
151         'avg_resources_node': "{0:10.0f}".format(avg_resources_node['Value']),
152         }
153
154     nodes = get_or_abort(puppetdb.nodes,
155         query='["and", {0}]'.format(
156             ", ".join('["=", "{0}", "{1}"]'.format(field, env)
157                 for field in ['catalog_environment', 'facts_environment'])),
158         unreported=app.config['UNRESPONSIVE_HOURS'],
159         with_status=True)
160
161     nodes_overview = []
162     stats = {
163         'changed': 0,
164         'unchanged': 0,
165         'failed': 0,
166         'unreported': 0,
167         'noop': 0
168         }
169
170     for node in nodes:
171         if node.status == 'unreported':
172             stats['unreported'] += 1
173         elif node.status == 'changed':
174             stats['changed'] += 1
175         elif node.status == 'failed':
176             stats['failed'] += 1
177         elif node.status == 'noop':
178             stats['noop'] += 1
179         else:
180             stats['unchanged'] += 1
181
182         if node.status != 'unchanged':
183             nodes_overview.append(node)
184
185     return render_template(
186         'index.html',
187         metrics=metrics,
188         nodes=nodes_overview,
189         stats=stats,
190         envs=envs,
191         current_env=env
192         )
```

**Comment by corey-hammerton** [comment]
Since we know that your instance is NOT appending the specific mbean to the URL when the code in pypuppetdb is clearly doing do I have to ask what version of python you are using?

Python's ``str.format()`` code, which is heavily used in these projects, was added in Python 2.6

**Comment by JuniperSpring** [comment]
Hmmm.....I'm using Python 2.6.6.

**Comment by JuniperSpring** [comment]
The metrics tab also has a problem with this.
If I click on a metric, the next page shows metrics with weird values.

Option: JMImplementation:type=MBeanServerDelegate
Value: /mbeans/JMImplementation%3Atype%3DMBeanServerDelegate

**Comment by corey-hammerton** [comment]
The value is the HTTP-escaped version of your selected option.

**Comment by JuniperSpring** [comment]
I uninstalled and then reinstalled everything and now it works perfectly. Not sure what was wrong, but it was definitely on my end. Thank you so much for your time and patience!

**Comment by corey-hammerton** [comment]
My next suggestion was to find and remove all ``.pyc`` files and go from there. Glad that it worked.
