### ISSUE TITLE
Error accessing Reports

### ISSUE THREAD

**Issue by Jmeyering** [puppet-community/puppetboard#192]
So this could totally be because I'm ignorant but I'm running into an issue viewing reports for my nodes, or viewing the nodes themselves

```
ERROR:puppetboard.app:Exception on /report/latest/{node} [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 484, in report_latest
    report = next(reports)
  File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/__init__.py", line 781, in reports
    metrics=report['metrics']['data'],
KeyError: u'data'
[pid: 30897|app: 0|req: 2/2] 71.87.62.139 () {44 vars in 832 bytes} [Thu Nov 19 21:51:37 2015] GET /report/latest/{node} => generated 3125 bytes in 14 msecs (HTTP/1.1 500) 2 headers in 100 bytes (1 switches on core 0)

```

Is what the log gives me any time I view a path starting in `/report` or `/node`

Any thoughts here?
Everything else seems to be working.

I can see run status on the dashboard along with number of changes just fine, when I click into them I get the above stack.

**Comment by Jmeyering** [comment]
Everything else seems to be working.

**Comment by corey-hammerton** [comment]
Do you use a PostgreSQL backend or HSQLDB?

Another similar issue was reported and they ended up using an HSQLDB backend. An excerpt from the documentation

```
Note: Expansion and the data field

For the following data structures the data field is only expanded for users running PostgreSQL. Expansion is not supported on HSQLDB, instead you must use the href field to construct a secondary query to retrieve that information.
```

**Comment by Jmeyering** [comment]
Ah it looks like I'm not using postgres. Will have to fix that

**Comment by Jmeyering** [comment]
Installed Postres and everything works great.
