### ISSUE TITLE
Metric route not working with Apache + mod_passenger

### ISSUE THREAD

**Issue by juliushaertl** [puppet-community/puppetboard#50]
When running puppetboard with Apache and Passenger on Ubuntu 12.04 with Python 2.7.3 the metric route doesn't work.

It seems like there is a problem with the url encoding with the pypuppetdb metric() method, but it works fine running dev.py and with mod_wsgi.

Log output of the failed HTTP call:
<pre>
[ pid=11081, time=2014-02-03 09:32:19,168 ]: Exception on /metric/com.jolbox.bonecp%253Atype%253DBoneCP [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app 
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "puppetboard/app.py", line 353, in metric
    metric = puppetdb.metric(metric)
  File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/__init__.py", line 321, in metric
    return self._query('mbean', path=metric)
  File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/__init__.py", line 267, in _query
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 683, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
</pre>

**Comment by corey-hammerton** [comment]
Are you still experiencing this problem with PuppetBoard 0.0.5?

**Comment by corey-hammerton** [comment]
Closing because of lack of activity
